# render.yaml — Django API on Render (fixed)
# - Binds Gunicorn to 0.0.0.0:$PORT
# - Health check hits /api/ (DRF root)
# - No uvicorn worker needed

databases:
  - name: royalroad-db
    plan: basic-256mb
    databaseName: royalroad
    user: royalroad

services:
  - type: web
    name: royalroad-api
    runtime: python
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/

    buildCommand: |
      pip install -r requirements.txt
      pip install "whitenoise[brotli]" gunicorn dj-database-url psycopg2-binary
      python manage.py collectstatic --no-input
      python manage.py migrate

    # IMPORTANT: bind to Render's PORT env on 0.0.0.0
    startCommand: gunicorn royalroad_clone.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: royalroad_clone.settings_prod
      - key: DATABASE_URL
        fromDatabase:
          name: royalroad-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      # allows any *.onrender.com host in your prod settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: "2"
