# Generated by Django 5.2.4 on 2025-07-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storytag',
            unique_together={('story', 'tag')},
        ),
    ]
