# Generated by Django 5.2.4 on 2025-07-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storytag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.story'),
        ),
    ]
