# Generated by Django 5.2.4 on 2025-08-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chapter_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.story'),
        ),
    ]
